import { BusinessOwner, EntitlementMeta, RoleCandidate } from "./types";

export const loggedInOwner: BusinessOwner = {
  ownerId: "11111111-1111-1111-1111-111111111111",
  name: "IAM Business Owner",
  title: "Director of Identity and Access Management",
  department: "Cybersecurity",
  domain: "IAM",
  businessResponsibility:
    "Responsible for identity and access management, access control, authentication systems, and governance of privileged access.",
};

export const entitlementMetadata: Record<string, EntitlementMeta> = {
  E001: {
    id: "E001",
    displayName: "Okta Admin Console",
    application: "Okta",
    sourceSystem: "IDP",
    description: "Administrative access to Okta tenant policies and application assignments.",
    sensitive: true,
    risk: "High",
  },
  E002: {
    id: "E002",
    displayName: "Okta Group Manager",
    application: "Okta",
    sourceSystem: "IDP",
    description: "Manage group memberships and delegated access assignments.",
    sensitive: true,
    risk: "High",
  },
  E003: {
    id: "E003",
    displayName: "SailPoint Access Review",
    application: "SailPoint",
    sourceSystem: "IGA",
    description: "Review and certify access packages during periodic campaigns.",
    sensitive: false,
    risk: "Medium",
  },
  E004: {
    id: "E004",
    displayName: "SailPoint Role Admin",
    application: "SailPoint",
    sourceSystem: "IGA",
    description: "Create and maintain birthright and requested role models.",
    sensitive: true,
    risk: "High",
  },
  E005: {
    id: "E005",
    displayName: "CyberArk Safe Operator",
    application: "CyberArk",
    sourceSystem: "PAM",
    description: "Operate privileged safes and manage credential checkout workflows.",
    sensitive: true,
    risk: "High",
  },
  E006: {
    id: "E006",
    displayName: "CyberArk Vault Auditor",
    application: "CyberArk",
    sourceSystem: "PAM",
    description: "Audit privileged session activity and safe access patterns.",
    sensitive: true,
    risk: "High",
  },
  E007: {
    id: "E007",
    displayName: "ServiceNow Access Request Approver",
    application: "ServiceNow",
    sourceSystem: "ITSM",
    description: "Approve or reject access requests submitted through request workflows.",
    sensitive: false,
    risk: "Medium",
  },
  E008: {
    id: "E008",
    displayName: "ServiceNow Catalog Publisher",
    application: "ServiceNow",
    sourceSystem: "ITSM",
    description: "Publish and maintain access catalog items and assignment rules.",
    sensitive: false,
    risk: "Medium",
  },
  E009: {
    id: "E009",
    displayName: "Active Directory Tier 1 Reset",
    application: "Active Directory",
    sourceSystem: "Directory",
    description: "Perform password resets and basic user unlock operations.",
    sensitive: true,
    risk: "Medium",
  },
  E010: {
    id: "E010",
    displayName: "Active Directory Group Write",
    application: "Active Directory",
    sourceSystem: "Directory",
    description: "Create and update security groups used across enterprise applications.",
    sensitive: true,
    risk: "High",
  },
  E011: {
    id: "E011",
    displayName: "Okta Access Analyst Reports",
    application: "Okta",
    sourceSystem: "IDP",
    description: "View access analytics and sign-in risk reports.",
    sensitive: false,
    risk: "Low",
  },
  E012: {
    id: "E012",
    displayName: "SailPoint Policy Exception Review",
    application: "SailPoint",
    sourceSystem: "IGA",
    description: "Review policy exceptions, toxic combinations, and risk decisions.",
    sensitive: true,
    risk: "High",
  },
};

export const roleCandidates: RoleCandidate[] = [
  {
    role_candidate_id: "global-17",
    role_name: "IAM Operations Admin",
    entitlement_set: ["E001", "E002", "E004", "E010"],
    support_score: 0.24,
    user_count: 126,
    cohort_scope: "global",
    candidate_type: "global",
    dominant_department: "Cybersecurity",
    dominant_job_title: "IAM Administrator",
    dominant_location: "Dublin",
    rule_confidence: 0.83,
    rule_lift: 2.1,
    status: "Pending",
    domain: "IAM",
    ownedApplications: ["Okta", "SailPoint", "Active Directory"],
    notes: "Strong bundle for provisioning administrators. Needs AD write control review.",
  },
  {
    role_candidate_id: "department-cybersecurity-3",
    role_name: "Privileged Access Analyst",
    entitlement_set: ["E005", "E006", "E011"],
    support_score: 0.18,
    user_count: 72,
    cohort_scope: "department=Cybersecurity",
    candidate_type: "cohort",
    dominant_department: "Cybersecurity",
    dominant_job_title: "PAM Analyst",
    dominant_location: "Cork",
    rule_confidence: 0.77,
    rule_lift: 1.84,
    status: "Needs Review",
    domain: "IAM",
    ownedApplications: ["CyberArk", "Okta"],
    notes: "Likely valid, but reporting access may be too broad for contractor populations.",
  },
  {
    role_candidate_id: "department-cybersecurity-7",
    role_name: "IGA Governance Reviewer",
    entitlement_set: ["E003", "E007", "E012"],
    support_score: 0.15,
    user_count: 58,
    cohort_scope: "department=Cybersecurity",
    candidate_type: "cohort",
    dominant_department: "Cybersecurity",
    dominant_job_title: "Access Governance Lead",
    dominant_location: "London",
    rule_confidence: 0.81,
    rule_lift: 1.68,
    status: "Approved",
    domain: "IAM",
    ownedApplications: ["SailPoint", "ServiceNow"],
    notes: "Approved as base governance reviewer bundle.",
  },
  {
    role_candidate_id: "global-24",
    role_name: "Identity Service Desk",
    entitlement_set: ["E007", "E008", "E009"],
    support_score: 0.13,
    user_count: 91,
    cohort_scope: "global",
    candidate_type: "global",
    dominant_department: "IT Operations",
    dominant_job_title: "Service Desk Analyst",
    dominant_location: "Manchester",
    rule_confidence: 0.71,
    rule_lift: 1.52,
    status: "Draft",
    domain: "IAM",
    ownedApplications: ["ServiceNow", "Active Directory"],
    notes: "Good operational pattern but may need split between request approval and reset tasks.",
  },
  {
    role_candidate_id: "location-dublin-2",
    role_name: "Identity Read-Only Auditor",
    entitlement_set: ["E003", "E006", "E011"],
    support_score: 0.1,
    user_count: 44,
    cohort_scope: "location=Dublin",
    candidate_type: "cohort",
    dominant_department: "Cybersecurity",
    dominant_job_title: "Security Auditor",
    dominant_location: "Dublin",
    rule_confidence: 0.69,
    rule_lift: 1.45,
    status: "Rejected",
    domain: "IAM",
    ownedApplications: ["SailPoint", "CyberArk", "Okta"],
    notes: "Rejected because auditors should not retain CyberArk operational entitlements.",
  },
  {
    role_candidate_id: "global-29",
    role_name: "Access Catalog Publisher",
    entitlement_set: ["E007", "E008", "E011"],
    support_score: 0.11,
    user_count: 63,
    cohort_scope: "global",
    candidate_type: "global",
    dominant_department: "Cybersecurity",
    dominant_job_title: "Access Request Analyst",
    dominant_location: "Dublin",
    rule_confidence: 0.73,
    rule_lift: 1.57,
    status: "Pending",
    domain: "IAM",
    ownedApplications: ["ServiceNow", "Okta"],
    notes: "Candidate likely overlaps with Identity Service Desk and may need merge review.",
  },
  {
    role_candidate_id: "department-cybersecurity-10",
    role_name: "Directory Governance Admin",
    entitlement_set: ["E003", "E009", "E010", "E012"],
    support_score: 0.09,
    user_count: 41,
    cohort_scope: "department=Cybersecurity",
    candidate_type: "cohort",
    dominant_department: "Cybersecurity",
    dominant_job_title: "Directory Security Engineer",
    dominant_location: "Dublin",
    rule_confidence: 0.74,
    rule_lift: 1.61,
    status: "Pending",
    domain: "IAM",
    ownedApplications: ["Active Directory", "SailPoint"],
    notes: "High-risk because it combines governance and write capability.",
  },
  {
    role_candidate_id: "global-33",
    role_name: "Privileged Review Coordinator",
    entitlement_set: ["E003", "E005", "E007"],
    support_score: 0.08,
    user_count: 36,
    cohort_scope: "global",
    candidate_type: "global",
    dominant_department: "Cybersecurity",
    dominant_job_title: "Privileged Access Coordinator",
    dominant_location: "Belfast",
    rule_confidence: 0.66,
    rule_lift: 1.34,
    status: "Draft",
    domain: "IAM",
    ownedApplications: ["CyberArk", "SailPoint", "ServiceNow"],
    notes: "Possible temporary role during quarterly access certification windows.",
  },
];
